In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
df.describe() #it gives the summary of numarical columns

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
df.describe(include = 'all')   #it gives the summary of all columns

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [18]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
Review Rating              0
dtype: int64

In [30]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [31]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
Review Rating             0
dtype: int64

In [35]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

df= df.rename(columns={'purchase_amount_(usd)' :'purchase_amount'})

In [36]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'review_rating_'],
      dtype='object')

In [39]:
#creating a column age_group which identify the age bracket in which customers will fall 

labels = ['young_adults', 'adult', 'middle_aged' , 'senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels = labels)

In [40]:
df[['age','age_group']].head(10)

   age     age_group
0   55   middle_aged
1   19  young_adults
2   50   middle_aged
3   21  young_adults
4   45   middle_aged
5   46   middle_aged
6   63        senior
7   27  young_adults
8   26  young_adults
9   57   middle_aged

In [52]:
#purchage frequency days it will convert the textual data in to number for easier understanding 
frequency_mapping ={
    'fortnightly':14,
    'weekly':7,
    'monthly':30,
    'quaterly':90,
    'bi-weekly':14,
    'annually':365,
    'every_3_months':90
}



df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [53]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                      NaN            Fortnightly
1                      NaN            Fortnightly
2                      NaN                 Weekly
3                      NaN                 Weekly
4                      NaN               Annually
5                      NaN                 Weekly
6                      NaN              Quarterly
7                      NaN                 Weekly
8                      NaN               Annually
9                      NaN              Quarterly

In [54]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [56]:
#checking redundancy 

(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [63]:
# dropping promo code used as the data is redundant 

df = df.drop('promo_code_used',axis=1)

KeyError: "['promo_code_used'] not found in axis"

In [64]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'review_rating_', 'age_group',
       '[purchase_frequency_days', 'purchase_frequency_days'],
      dtype='object')

In [65]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\shikh\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\shikh\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\shikh\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   -------------------------- ------------- 1.8/2.8 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 10.0 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [66]:
pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [68]:
import urllib.parse
from sqlalchemy import create_engine, text

# 1. Define your connection variables
USER = 'root'                     # Default MySQL user
PASSWORD = 'Shikhar@12'        # Replace with your actual password
HOST = 'localhost'
PORT = '3306'                     # Standard MySQL port
DATABASE = 'customer_sales'      # The database you created earlier

# Safely encode the password in case it has special characters like @, #, or /
safe_password = urllib.parse.quote_plus(PASSWORD)

# 2. Build the connection string for MySQL
connection_string = f"mysql+pymysql://{USER}:{safe_password}@{HOST}:{PORT}/{DATABASE}"

# 3. Create the SQLAlchemy Engine
engine = create_engine(connection_string)

# 4. Test the connection
try:
    with engine.connect() as connection:
        # Ask MySQL for its version to prove we are connected
        result = connection.execute(text("SELECT VERSION();"))
        print("Successfully connected to MySQL!")
        print(f"MySQL Version: {result.fetchone()[0]}")
except Exception as e:
    print("Connection failed. Error:")
    print(e)

Successfully connected to MySQL!
MySQL Version: 8.0.46

In [70]:
#creating a table 
table_name = "customer"
df.to_sql(table_name,engine,if_exists="replace",index = False)

3900